"""The seal covers the data only (docs/specs/SPEC_F1_data_only_seal.md, #270): two runs over one snapshot
with the same parameters hash the same whoever runs them and whenever, because a report's data ends at the
snapshot's stamp (docs/specs/SPEC_F7_snapshot_clock.md, #592); the snapshot, the parameters and the coverage are
sealed; page one still shows the run; the .json alone reproduces the hash."""
from __future__ import annotations

import hashlib
import importlib.util
import inspect
import json
import sys
from datetime import timedelta
from pathlib import Path

import pytest

from gsd.reporting.catalogue import REGISTRY, RunContext, validate_params
from gsd.reporting.catalogue import common
from gsd.reporting.catalogue.common import assemble
from gsd.reporting import model
from gsd.reporting.config import ReportSettings
from gsd.reporting.model import Report
from gsd.reporting.snapshot import Snapshot
from reporting_seed import CLUSTER, NOW, seed_store, write_snapshot

LOCAL = Path(__file__).resolve().parents[1]
DOCS = LOCAL.parent / "docs"

#: What a report needs before it builds (the catalogue suite's defaults).
PARAMS = {
    "namespace-access": {"namespaces": "prod-ns,dev-ns"},
    "access-certification": {"campaign": "Q3 2026", "due": "2026-10-01", "reviewer": "Jane Reviewer"},
}
#: The five reports whose window, cutoff or overdue state ends at the snapshot's stamp (#592), each with the
#: parameters that put a seeded row on that edge: on main, a run two days later moved each of them (SPEC_F7 §2.3).
SNAPSHOT_CLOCK = {"login-activity": {}, "groups": {"window_days": 1}, "dormant-access": {"dormant_days": 1},
                  "groupsync-health": {}, "compliance-snapshot": {}}
#: The .json keys before SPEC_F1; none is removed or renamed.
JSON_KEYS = {"name", "cluster", "params", "coverage", "totals", "truncated", "include_members", "sections", "title",
             "api_url", "generated_at", "generated_by", "generated_by_note", "run_id", "provenance", "sha256"}


def _snapshot(tmp_path: Path, **seed) -> Snapshot:
    store = seed_store(str(tmp_path / "writer.db"), **seed)
    directory = tmp_path / "snapshots"
    directory.mkdir()
    try:
        return Snapshot(write_snapshot(store, directory))
    finally:
        store.close()


@pytest.fixture(scope="module")
def snap(tmp_path_factory):
    snapshot = _snapshot(tmp_path_factory.mktemp("seal"))
    yield snapshot
    snapshot.close()


def _run(snapshot: Snapshot, name: str, *, now=NOW, run_id="20260906T120000.000000Z-ab12", viewer="alice",
         note="proxy-verified", params=None, **settings) -> Report:
    spec, build = REGISTRY[name]
    info = snapshot.info()
    ctx = RunContext(settings=ReportSettings(**{"login_capture_enabled": True, **settings}),
                     cluster=snapshot.cluster(CLUSTER), now=now, run_id=run_id, generated_by=viewer,
                     generated_by_note=note, snapshot_stamp=info.stamp, snapshot_age_seconds=info.age_seconds(now),
                     schema_version=info.schema_version)
    p = validate_params(spec, {**PARAMS.get(name, {}), **(params or {})})
    return assemble(spec, snapshot, ctx, p, build(snapshot, ctx, p))


def _other_run(snapshot: Snapshot, name: str, **over) -> Report:
    """The same report over the same snapshot by another viewer, under another run id, two minutes later."""
    return _run(snapshot, name, now=NOW + timedelta(minutes=2), run_id="20260906T120200.000000Z-cd34", viewer="bob",
                note="schedule:nightly", **over)


def _page_one(report: Report) -> dict:
    return dict(report.sections[0].blocks[0].items)


@pytest.mark.parametrize("name", list(REGISTRY))
def test_t270_1_two_runs_over_one_snapshot_hash_the_same(snap, name):
    """Without SPEC_F1 every report fails: page one's Generated at, Generated by and Run id rows, and the
    snapshot's age in its Data as of row, were inside the hash."""
    first, second = _run(snap, name), _other_run(snap, name)
    assert first.sha256 == second.sha256, name
    one, two = _page_one(first), _page_one(second)
    assert one["Run id"] != two["Run id"] and one["Generated by"] != two["Generated by"], "page one still shows the run"
    assert one["Generated at (UTC)"] != two["Generated at (UTC)"]


@pytest.mark.parametrize("name", sorted(SNAPSHOT_CLOCK))
def test_t592_1_two_runs_two_days_apart_over_one_snapshot_hash_the_same(snap, name):
    """#592: a report's window, cutoff or overdue state ends at the snapshot's stamp, so a run two days later over
    the same snapshot states the same data; page one's Generated at still says when each ran. Without the change
    each of the five differs (SPEC_F7 §2.3): login-activity's Window `To`, the one-day change window of groups, the
    one-day dormancy cutoff, groupsync-health's overdue state and compliance-snapshot's Overdue count."""
    params = SNAPSHOT_CLOCK[name]
    first = _run(snap, name, params=params)
    later = _run(snap, name, now=NOW + timedelta(days=2), run_id="20260908T120000.000000Z-cd34", viewer="bob",
                 params=params)
    assert first.sha256 == later.sha256, name
    assert _page_one(first)["Generated at (UTC)"] == "2026-09-06T12:00:00Z"
    assert _page_one(later)["Generated at (UTC)"] == "2026-09-08T12:00:00Z"


def test_t270_3_the_renderer_marking_interval_and_pdf_rows_are_not_sealed(snap, monkeypatch):
    """A release, a new marking, a new binding interval or another PDF variant re-labels the same evidence.
    Without SPEC_F1 the Handling, Report service, Data as of and PDF rows were inside the hash."""
    first = _run(snap, "groups")
    monkeypatch.setattr(common, "__version__", "9.9.9")
    second = _run(snap, "groups", marking="Handling: restricted", binding_interval_seconds=900,
                  git_commit="0123456789ab-dirty", pdf_variant="pdf/a-3b")
    assert first.sha256 == second.sha256
    rows = _page_one(second)
    assert rows["Handling"] == "Handling: restricted"
    assert rows["Report service"].startswith("9.9.9 @ 0123456789ab-dirty")
    assert "bindings refresh every 900 s" in rows["Data as of"] and rows["PDF"].startswith("variant pdf/a-3b")


@pytest.mark.parametrize("change", ["snapshot", "parameters", "coverage"])
def test_t270_4_the_data_changes_the_hash_and_the_run_does_not(snap, tmp_path, change):
    """The control (another viewer, run id and clock) fails without SPEC_F1; the data assertion holds the seal
    against leaving out too much, and passes with or without it."""
    name = "groupsync-health"
    base = _run(snap, name)
    assert _other_run(snap, name).sha256 == base.sha256, "the control: only the run differs"
    if change == "snapshot":
        other = _snapshot(tmp_path, reconcile_error=False)
        try:
            changed = _run(other, name)
        finally:
            other.close()
        assert changed.canonical()["sections"] != base.canonical()["sections"], "the seed change reaches the data"
    elif change == "parameters":
        changed = _run(snap, name, params={"window_days": 7})
    else:
        changed = _run(snap, name, login_capture_enabled=False)
        assert changed.coverage != base.coverage
    assert changed.sha256 != base.sha256, change


def test_t270_5_the_json_alone_reproduces_the_hash(snap):
    """The .json keeps every key and every section, page one included, and the hash is the sha256 of its
    canonical keys with the sections narrowed to the sealed ones. Without SPEC_F1: no `sealed_provenance`."""
    report = _run(snap, "groups")
    doc = json.loads(report.to_json())
    assert JSON_KEYS <= set(doc), JSON_KEYS - set(doc)
    assert [s["title"] for s in doc["sections"]] == [s.title for s in report.sections], "page one is in the .json"
    assert doc["sections"][0]["sealed"] is False and all(s["sealed"] for s in doc["sections"][1:])
    sealed = {key: doc[key] for key in ("name", "cluster", "api_url", "params", "coverage", "totals", "truncated",
                                         "include_members", "sealed_provenance")}
    sealed["sections"] = [s for s in doc["sections"] if s["sealed"]]
    digest = hashlib.sha256(json.dumps(sealed, sort_keys=True, separators=(",", ":"), default=str).encode("utf-8"))
    assert digest.hexdigest() == doc["sha256"] == report.sha256


def test_t270_6_a_new_snapshot_of_the_same_data_is_new_evidence(tmp_path):
    """The stamp is sealed (SPEC_F1 §3.2): two snapshots of one database differ in their stamp and nothing
    else, and hash differently. Without SPEC_F1 the canonical document has no `sealed_provenance`."""
    store = seed_store(str(tmp_path / "writer.db"))
    directory = tmp_path / "snapshots"
    directory.mkdir()
    try:
        first = Snapshot(write_snapshot(store, directory))
        second = Snapshot(write_snapshot(store, directory, at=NOW + timedelta(minutes=5)))
    finally:
        store.close()
    try:
        one, two = _run(first, "groups"), _run(second, "groups")
    finally:
        first.close()
        second.close()
    assert one.sha256 != two.sha256
    a, b = one.canonical(), two.canonical()
    assert a["sealed_provenance"].pop("snapshot_stamp") != b["sealed_provenance"].pop("snapshot_stamp")
    assert a == b, "the stamp is the only difference"


def _integrity_check():
    """The e2e walk's integrity script, loaded from its file (it is not a package module)."""
    module_spec = importlib.util.spec_from_file_location("integrity_check", LOCAL / "e2e-walk" / "integrity_check.py")
    integrity = importlib.util.module_from_spec(module_spec)
    module_spec.loader.exec_module(integrity)
    return integrity


def test_t270_7_the_walks_integrity_check_recomputes_the_seal(snap):
    """The e2e walk recomputes each downloaded report's hash from its .json (local-development/e2e-walk/
    integrity_check.py), so its recipe must be the model's. Without Block 13 it has no `recompute`, and its
    old key list seals page one and neither `api_url` nor `sealed_provenance`."""
    integrity = _integrity_check()
    for name in REGISTRY:
        report = _run(snap, name)
        assert integrity.recompute(json.loads(report.to_json())) == report.sha256, name


def _walk_dir(tmp_path: Path, docs: dict[str, dict]) -> Path:
    """A walk's run directory holding these .json artefacts and the run records the page polled for them."""
    run = tmp_path / "walk"
    (run / "reports").mkdir(parents=True)
    steps = []
    for stem, doc in docs.items():
        (run / "reports" / f"{stem}.json").write_text(json.dumps(doc))
        steps.append({"run": {"id": doc["run_id"], "sha256": doc["sha256"]}})
    (run / "results.json").write_text(json.dumps({"steps": steps}))
    return run


def test_t270_8_a_json_written_before_4_1_is_a_fail_row_not_a_crash(snap, tmp_path, monkeypatch):
    """A .json written before 4.1.0 has no `sealed_provenance` and no `sealed` flags. The integrity stage writes
    it as a FAIL row and carries on; a KeyError there wrote no integrity.jsonl, and the walk's document stage
    (build_doc.py) then died reading it."""
    old = json.loads(_run(snap, "groups", run_id="r-old").to_json())
    del old["sealed_provenance"]
    for section in old["sections"]:
        del section["sealed"]
    new = json.loads(_run(snap, "groups", run_id="r-new").to_json())
    run = _walk_dir(tmp_path, {"a-old": old, "b-new": new})
    monkeypatch.setattr(sys, "argv", ["integrity_check.py", str(run)])
    assert _integrity_check().main() == 1
    rows = [json.loads(line) for line in (run / "integrity.jsonl").read_text().splitlines()]
    assert [row["recomputed_matches"] for row in rows] == [False, True]


def test_t270_9_only_page_one_rides_outside_the_seal(snap):
    """The model leaves exactly one section out of the hash: page one, the first. A .json carrying any other
    unsealed section, or page one marked sealed, does not verify: otherwise a section added to a .json with
    `"sealed": false` would pass the walk's check against the run record's hash."""
    integrity = _integrity_check()
    doc = json.loads(_run(snap, "groups").to_json())
    assert integrity.recompute(doc) == doc["sha256"]
    added = {**doc, "sections": [*doc["sections"], {"title": "Attestation", "page_break": False, "sealed": False,
                                                    "blocks": [{"kind": "note", "text": "approved", "level": "note"}]}]}
    assert integrity.recompute(added) is None
    page_one_sealed = {**doc, "sections": [{**doc["sections"][0], "sealed": True}, *doc["sections"][1:]]}
    assert integrity.recompute(page_one_sealed) is None


def test_t592_2_no_report_reads_the_generation_clock_into_its_data():
    """#592: no builder reads `ctx.now` (page one, in common.py, does: Generated at and the snapshot's age); the five
    that end a window, a cutoff or an overdue state at the snapshot's stamp are named where the seal is described.
    Without the change those five read `ctx.now`, and the model's docstrings promise less."""
    sources = {name: inspect.getsource(inspect.getmodule(build)) for name, (_, build) in REGISTRY.items()}
    assert not [name for name, source in sources.items() if "ctx.now" in source]
    assert {name for name, source in sources.items() if "ctx.snapshot_at" in source} == set(SNAPSHOT_CLOCK)
    design = (DOCS / "DESIGN_reporting_service.md").read_text()
    paragraph = design[design.index("**What the sha256 covers (SPEC_F1, #270).**"):]
    paragraph = paragraph[:paragraph.index("\n\n")]
    assert "end at the\nsnapshot's stamp, not at the generation time" in paragraph and "generation clock" not in paragraph
    assert not [n for n in sorted(SNAPSHOT_CLOCK) if f"`{n}`" not in paragraph]
    assert "generation clock" not in model.__doc__ and "generation clock" not in model.Report.canonical.__doc__


def test_t270_11_the_walk_document_states_the_recipe_the_check_runs():
    """build_doc.py prints the seal's recipe in the walk document's integrity section: it names every key the
    integrity check seals and says page one is left out."""
    source = (LOCAL / "e2e-walk" / "build_doc.py").read_text()
    sentence = source[source.index("Every report is sealed with"):source.index("sorted keys, compact separators")]
    assert not [k for k in _integrity_check().CANONICAL if k not in sentence], sentence
    assert "page one" in sentence and "sealed" in sentence.replace("sealed_provenance", "")
