"""The seal covers the data only (docs/specs/SPEC_F1_data_only_seal.md, #270): two runs over one snapshot
with the same parameters hash the same whoever runs them and whenever; the snapshot, the parameters and the
coverage are sealed; page one still shows the run; the .json alone reproduces the hash."""
from __future__ import annotations

import hashlib
import importlib.util
import json
from datetime import timedelta
from pathlib import Path

import pytest

from gsd.reporting.catalogue import REGISTRY, RunContext, validate_params
from gsd.reporting.catalogue import common
from gsd.reporting.catalogue.common import assemble
from gsd.reporting.config import ReportSettings
from gsd.reporting.model import Report
from gsd.reporting.snapshot import Snapshot
from reporting_seed import CLUSTER, NOW, seed_store, write_snapshot

#: What a report needs before it builds (the catalogue suite's defaults).
PARAMS = {
    "namespace-access": {"namespaces": "prod-ns,dev-ns"},
    "access-certification": {"campaign": "Q3 2026", "due": "2026-10-01", "reviewer": "Jane Reviewer"},
}
#: login-activity's Window prints the generation clock as its `To`: data anchored to the run (SPEC_F1,
#: Orchestrator's notes 1), so two of its runs agree only at one clock.
CLOCK_ANCHORED = {"login-activity"}
#: The .json keys before SPEC_F1; none is removed or renamed.
JSON_KEYS = {"name", "cluster", "params", "coverage", "totals", "truncated", "include_members", "sections", "title",
             "api_url", "generated_at", "generated_by", "generated_by_note", "run_id", "provenance", "sha256"}


def _snapshot(tmp_path: Path, **seed) -> Snapshot:
    store = seed_store(str(tmp_path / "writer.db"), **seed)
    directory = tmp_path / "snapshots"
    directory.mkdir()
    try:
        return Snapshot(write_snapshot(store, directory))
    finally:
        store.close()


@pytest.fixture(scope="module")
def snap(tmp_path_factory):
    snapshot = _snapshot(tmp_path_factory.mktemp("seal"))
    yield snapshot
    snapshot.close()


def _run(snapshot: Snapshot, name: str, *, now=NOW, run_id="20260906T120000.000000Z-ab12", viewer="alice",
         note="proxy-verified", params=None, **settings) -> Report:
    spec, build = REGISTRY[name]
    info = snapshot.info()
    ctx = RunContext(settings=ReportSettings(**{"login_capture_enabled": True, **settings}),
                     cluster=snapshot.cluster(CLUSTER), now=now, run_id=run_id, generated_by=viewer,
                     generated_by_note=note, snapshot_stamp=info.stamp, snapshot_age_seconds=info.age_seconds(now),
                     schema_version=info.schema_version)
    p = validate_params(spec, {**PARAMS.get(name, {}), **(params or {})})
    return assemble(spec, snapshot, ctx, p, build(snapshot, ctx, p))


def _other_run(snapshot: Snapshot, name: str, **over) -> Report:
    """The same report over the same snapshot by another viewer, under another run id, two minutes later
    (at the same clock for a clock-anchored report)."""
    later = NOW if name in CLOCK_ANCHORED else NOW + timedelta(minutes=2)
    return _run(snapshot, name, now=later, run_id="20260906T120200.000000Z-cd34", viewer="bob",
                note="schedule:nightly", **over)


def _page_one(report: Report) -> dict:
    return dict(report.sections[0].blocks[0].items)


@pytest.mark.parametrize("name", list(REGISTRY))
def test_t270_1_two_runs_over_one_snapshot_hash_the_same(snap, name):
    """Without SPEC_F1 every report fails: page one's Generated at, Generated by and Run id rows, and the
    snapshot's age in its Data as of row, were inside the hash."""
    first, second = _run(snap, name), _other_run(snap, name)
    assert first.sha256 == second.sha256, name
    one, two = _page_one(first), _page_one(second)
    assert one["Run id"] != two["Run id"] and one["Generated by"] != two["Generated by"], "page one still shows the run"
    if name not in CLOCK_ANCHORED:
        assert one["Generated at (UTC)"] != two["Generated at (UTC)"]


def test_t270_2_login_activity_differs_only_in_its_window_when_the_clock_moves(snap):
    """The measured limit (SPEC_F1, Orchestrator's notes 1): at another clock, login-activity's sealed data
    differs in its Window block and nowhere else. Without SPEC_F1 page one differs too."""
    first = _run(snap, "login-activity")
    second = _run(snap, "login-activity", now=NOW + timedelta(minutes=2), run_id="20260906T120200.000000Z-cd34",
                  viewer="bob")
    assert first.sha256 != second.sha256

    def without_window(report: Report) -> dict:
        doc = report.canonical()
        for section in doc["sections"]:
            section["blocks"] = [b for b in section["blocks"] if not (b["kind"] == "kv" and b["title"] == "Window")]
        return doc

    assert without_window(first) == without_window(second)


def test_t270_3_the_renderer_marking_interval_and_pdf_rows_are_not_sealed(snap, monkeypatch):
    """A release, a new marking, a new binding interval or another PDF variant re-labels the same evidence.
    Without SPEC_F1 the Handling, Report service, Data as of and PDF rows were inside the hash."""
    first = _run(snap, "groups")
    monkeypatch.setattr(common, "__version__", "9.9.9")
    second = _run(snap, "groups", marking="Handling: restricted", binding_interval_seconds=900,
                  git_commit="0123456789ab-dirty", pdf_variant="pdf/a-3b")
    assert first.sha256 == second.sha256
    rows = _page_one(second)
    assert rows["Handling"] == "Handling: restricted"
    assert rows["Report service"].startswith("9.9.9 @ 0123456789ab-dirty")
    assert "bindings refresh every 900 s" in rows["Data as of"] and rows["PDF"].startswith("variant pdf/a-3b")


@pytest.mark.parametrize("change", ["snapshot", "parameters", "coverage"])
def test_t270_4_the_data_changes_the_hash_and_the_run_does_not(snap, tmp_path, change):
    """The control (another viewer, run id and clock) fails without SPEC_F1; the data assertion holds the seal
    against leaving out too much, and passes with or without it."""
    name = "groupsync-health"
    base = _run(snap, name)
    assert _other_run(snap, name).sha256 == base.sha256, "the control: only the run differs"
    if change == "snapshot":
        other = _snapshot(tmp_path, reconcile_error=False)
        try:
            changed = _run(other, name)
        finally:
            other.close()
        assert changed.canonical()["sections"] != base.canonical()["sections"], "the seed change reaches the data"
    elif change == "parameters":
        changed = _run(snap, name, params={"window_days": 7})
    else:
        changed = _run(snap, name, login_capture_enabled=False)
        assert changed.coverage != base.coverage
    assert changed.sha256 != base.sha256, change


def test_t270_5_the_json_alone_reproduces_the_hash(snap):
    """The .json keeps every key and every section, page one included, and the hash is the sha256 of its
    canonical keys with the sections narrowed to the sealed ones. Without SPEC_F1: no `sealed_provenance`."""
    report = _run(snap, "groups")
    doc = json.loads(report.to_json())
    assert JSON_KEYS <= set(doc), JSON_KEYS - set(doc)
    assert [s["title"] for s in doc["sections"]] == [s.title for s in report.sections], "page one is in the .json"
    assert doc["sections"][0]["sealed"] is False and all(s["sealed"] for s in doc["sections"][1:])
    sealed = {key: doc[key] for key in ("name", "cluster", "api_url", "params", "coverage", "totals", "truncated",
                                         "include_members", "sealed_provenance")}
    sealed["sections"] = [s for s in doc["sections"] if s["sealed"]]
    digest = hashlib.sha256(json.dumps(sealed, sort_keys=True, separators=(",", ":"), default=str).encode("utf-8"))
    assert digest.hexdigest() == doc["sha256"] == report.sha256


def test_t270_6_a_new_snapshot_of_the_same_data_is_new_evidence(tmp_path):
    """The stamp is sealed (SPEC_F1 §3.2): two snapshots of one database differ in their stamp and nothing
    else, and hash differently. Without SPEC_F1 the canonical document has no `sealed_provenance`."""
    store = seed_store(str(tmp_path / "writer.db"))
    directory = tmp_path / "snapshots"
    directory.mkdir()
    try:
        first, second = Snapshot(write_snapshot(store, directory)), Snapshot(write_snapshot(store, directory))
    finally:
        store.close()
    try:
        one, two = _run(first, "groups"), _run(second, "groups")
    finally:
        first.close()
        second.close()
    assert one.sha256 != two.sha256
    a, b = one.canonical(), two.canonical()
    assert a["sealed_provenance"].pop("snapshot_stamp") != b["sealed_provenance"].pop("snapshot_stamp")
    assert a == b, "the stamp is the only difference"


def test_t270_7_the_walks_integrity_check_recomputes_the_seal(snap):
    """The e2e walk recomputes each downloaded report's hash from its .json (local-development/e2e-walk/
    integrity_check.py), so its recipe must be the model's. Without Block 13 it has no `recompute`, and its
    old key list seals page one and neither `api_url` nor `sealed_provenance`."""
    path = Path(__file__).resolve().parents[1] / "e2e-walk" / "integrity_check.py"
    module_spec = importlib.util.spec_from_file_location("integrity_check", path)
    integrity = importlib.util.module_from_spec(module_spec)
    module_spec.loader.exec_module(integrity)
    for name in REGISTRY:
        report = _run(snap, name)
        assert integrity.recompute(json.loads(report.to_json())) == report.sha256, name
