"""The ticket key (#392, docs/specs/SPEC_F6_ticket_signing_key.md): viewers' tickets are signed with a key of their
own, never with the service token the schedule Jobs and the poller hold, so a token holder can no longer sign a
ticket naming anybody and make that name a run's "Generated by". T392-1 to T392-7, one per rule of SPEC_F6 §4.1."""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
import os
import pathlib
import re
import shutil
import subprocess
import time

import pytest
from fastapi.testclient import TestClient

from gsd.activity import USER_HEADER
from gsd.api import build_app
from gsd.config import ClusterConfig, Settings
from gsd.reporting import REPORT_PREFIX, TICKET_HEADER
from gsd.reporting.config import load_report_settings
from gsd.reporting.server import build_report_app
from gsd.reporting.ticket import mint
from reporting_seed import CLUSTER, seeded_dirs

REPO = pathlib.Path(__file__).resolve().parents[2]
CHART = REPO / "charts" / "group-sync-dashboard"
TOKEN = b"T" * 48          # the service token: the schedule Jobs, the poller and housekeeping present it
KEY = b"K" * 48            # the ticket key: the dashboard signs with it, the report pod verifies with it
OLD_KEY = b"O" * 48        # a rotated-out ticket key


def _service(tmp_path, monkeypatch, *, key: bytes | None = KEY, previous: bytes | None = None) -> TestClient:
    """The report service as the chart starts it: settings from the environment, both secrets from mounted files."""
    tmp_path.mkdir(parents=True, exist_ok=True)
    snapshots, artifacts = seeded_dirs(tmp_path)
    secrets_dir = tmp_path / "secrets"
    secrets_dir.mkdir(exist_ok=True)
    (secrets_dir / "token").write_bytes(TOKEN + b"\n")
    for name, value in (("key", key), ("previous", previous)):
        if value is not None:
            (secrets_dir / name).write_bytes(value + b"\n")
    env = {"GSD_REPORT_TOKEN_FILE": secrets_dir / "token", "GSD_REPORT_TICKET_KEY_FILE": secrets_dir / "key",
           "GSD_REPORT_TICKET_PREVIOUS_KEY_FILE": secrets_dir / "previous", "GSD_REPORT_SNAPSHOT_DIR": snapshots,
           "GSD_REPORT_ARTIFACT_DIR": artifacts, "GSD_REPORT_PDF_ENABLED": "false", "GSD_REPORT_PDF_VARIANT": ""}
    for name, value in env.items():
        monkeypatch.setenv(name, str(value))
    return TestClient(build_report_app(load_report_settings()))


def _viewer(key: bytes, user: str) -> dict:
    return {TICKET_HEADER: mint(key, user, "all", 300), USER_HEADER: user}


def _version_one(key: bytes, user: str) -> str:
    """A ticket of the format before #392, `<payload>.<signature>`, signed the way the old dashboard signed it."""
    now = int(time.time())
    payload = json.dumps({"v": 1, "viewer": user, "tier": "all", "iat": now, "exp": now + 300, "nonce": "n"},
                         sort_keys=True, separators=(",", ":")).encode()
    b64 = lambda raw: base64.urlsafe_b64encode(raw).rstrip(b"=").decode()     # noqa: E731
    return f"{b64(payload)}.{b64(hmac.new(key, payload, hashlib.sha256).digest())}"


def test_t392_1_a_ticket_signed_with_the_service_token_is_refused(tmp_path, monkeypatch):
    """The issue's forging test. Before #392 both tickets below verified: the service token WAS the ticket key, so
    whoever held it could start a run attributed to anybody. Now neither is accepted and no run is recorded."""
    client = _service(tmp_path, monkeypatch)
    body = {"report": "groups", "cluster": CLUSTER}
    forged = client.post(f"{REPORT_PREFIX}/api/runs", json=body, headers=_viewer(TOKEN, "mallory"))
    assert forged.status_code == 403, forged.text
    # the earlier format, signed with the token as the old dashboard did: told to mint again, never accepted
    old_shape = client.post(f"{REPORT_PREFIX}/api/runs", json=body,
                            headers={TICKET_HEADER: _version_one(TOKEN, "mallory"), USER_HEADER: "mallory"})
    assert old_shape.status_code == 401, old_shape.text
    runs = client.get(f"{REPORT_PREFIX}/api/runs", headers={"Authorization": f"Bearer {TOKEN.decode()}"}).json()["runs"]
    assert not [r for r in runs if r["generated_by"] == "mallory"], runs
    # and the dashboard's own ticket still works
    real = client.get(f"{REPORT_PREFIX}/api/reports", headers=_viewer(KEY, "root"))
    assert real.status_code == 200 and real.json()["viewer"] == "root"


def test_t392_2_the_service_token_authenticates_as_before_and_is_no_ticket_key(tmp_path, monkeypatch):
    """Must not change: the bearer still authenticates the schedule Jobs and the dashboard's poll, a wrong bearer is
    still 401, and a viewer's ticket still cannot read the usage feed. The ticket key is not a bearer."""
    client = _service(tmp_path, monkeypatch)
    service = {"Authorization": f"Bearer {TOKEN.decode()}"}
    assert client.get(f"{REPORT_PREFIX}/api/usage", headers=service).status_code == 200
    run = client.post(f"{REPORT_PREFIX}/api/runs", json={"report": "groups", "schedule": "nightly"}, headers=service)
    assert run.status_code in (200, 202), run.text
    assert all(r["generated_by"] == "schedule:nightly" for r in run.json()["runs"])
    assert client.get(f"{REPORT_PREFIX}/api/usage", headers={"Authorization": "Bearer wrong"}).status_code == 401
    assert client.get(f"{REPORT_PREFIX}/api/usage", headers={"Authorization": f"Bearer {KEY.decode()}"}).status_code == 401
    assert client.get(f"{REPORT_PREFIX}/api/usage", headers=_viewer(KEY, "root")).status_code == 403
    assert client.get(f"{REPORT_PREFIX}/api/reports").status_code == 401


def test_t392_3_a_rotation_accepts_both_keys_and_its_close_refuses_the_old(tmp_path, monkeypatch):
    """The window: with `previous` mounted, a ticket the dashboard signed before its restart (the old key) and one
    signed after (the new key) both verify; once `previous` is removed, the old key's ticket is refused (403)."""
    old_ticket, new_ticket = _viewer(OLD_KEY, "root"), _viewer(KEY, "root")
    opened = _service(tmp_path / "open", monkeypatch, key=KEY, previous=OLD_KEY)
    assert opened.get(f"{REPORT_PREFIX}/api/reports", headers=old_ticket).status_code == 200
    assert opened.get(f"{REPORT_PREFIX}/api/reports", headers=new_ticket).status_code == 200
    closed = _service(tmp_path / "closed", monkeypatch, key=KEY)
    assert closed.get(f"{REPORT_PREFIX}/api/reports", headers=new_ticket).status_code == 200
    assert closed.get(f"{REPORT_PREFIX}/api/reports", headers=old_ticket).status_code == 403
    assert opened.get(f"{REPORT_PREFIX}/api/reports", headers=_viewer(TOKEN, "root")).status_code == 403


@pytest.mark.parametrize("key, previous, why", [
    (None, None, "No such file"),
    (b"short", None, "shorter than 32 bytes"),
    (TOKEN, None, "the service token's value"),
    (KEY, TOKEN, "the service token's value"),
    (KEY, b"short", "shorter than 32 bytes"),
])
def test_t392_4_an_unusable_ticket_key_stops_both_pods(tmp_path, monkeypatch, key, previous, why):
    """A key that is missing, short, or the token's own bytes is a startup failure in the report pod and in the
    dashboard, the repository's rule for a module that is on and cannot work."""
    with pytest.raises((OSError, ValueError), match=why):
        _service(tmp_path, monkeypatch, key=key, previous=previous)
    token, key_file = tmp_path / "dash-token", tmp_path / "dash-key"
    token.write_bytes(TOKEN)
    if key is not None:
        key_file.write_bytes(key)
    settings = Settings(clusters=[ClusterConfig("c1", "https://x", token_env="T")], db_path=str(tmp_path / "t.db"),
                        oauth_proxy_enabled=True, reporting_url="https://r", reporting_token_file=str(token),
                        reporting_ticket_key_file=str(key_file))
    if previous is None:
        with pytest.raises(RuntimeError, match="ticket key is unusable"):
            build_app(settings, run_poller=False, tier_resolver=lambda _v: "all")


def test_t392_5_a_ticket_of_the_earlier_format_is_told_to_mint_again(tmp_path, monkeypatch):
    """A page open across the upgrade holds a version-1 ticket: 401, which reportFetch answers by minting once, and
    not the 403 refusal card, which an administrator would otherwise see until the ticket aged out."""
    client = _service(tmp_path, monkeypatch)
    r = client.get(f"{REPORT_PREFIX}/api/reports", headers={TICKET_HEADER: _version_one(KEY, "root"), USER_HEADER: "root"})
    assert r.status_code == 401 and r.json()["detail"] == "ticket is from an earlier release; mint a new ticket"
    page = (REPO / "local-development" / "gsd" / "static" / "index.html").read_text()
    assert "if (res.status === 401 && !retried) return reportFetch(path, init, true);" in page


def _render(*sets: str) -> list[dict]:
    import yaml
    args = ["helm", "template", "t", str(CHART), "-n", "x", "--set", "ingress.host=h"]
    for s in sets:
        args += ["--set", s]
    done = subprocess.run(args, capture_output=True, text=True, timeout=120)
    assert done.returncode == 0, done.stderr
    return [d for d in yaml.safe_load_all(done.stdout) if d]


def _pod(doc: dict) -> dict:
    spec = doc["spec"]["jobTemplate"]["spec"] if doc["kind"] == "CronJob" else doc["spec"]
    return spec["template"]["spec"]


@pytest.mark.skipif(shutil.which("helm") is None, reason="helm not installed")
def test_t392_6_the_key_is_minted_and_mounted_in_the_two_pods_and_never_in_a_schedule_job():
    docs = _render("reporting.schedules[0].name=nightly", "reporting.schedules[0].report=groups",
                   "reporting.schedules[0].schedule=0 1 * * *",
                   "reporting.schedules[1].name=hook", "reporting.schedules[1].report=groups",
                   "reporting.schedules[1].schedule=0 2 * * *", "reporting.schedules[1].deliver.kind=webhook",
                   "reporting.schedules[1].deliver.webhookUrlSecret.name=hook-url")
    name = "t-group-sync-dashboard-report-ticket-key"
    assert not [d for d in docs if d["kind"] == "Secret" and d["metadata"]["name"] == name], "minted, never rendered"
    job = next(d for d in docs if d["kind"] == "Job" and d["metadata"]["name"].endswith("-secrets-mint"))
    env = {e["name"]: e["value"] for e in job["spec"]["template"]["spec"]["containers"][0]["env"]}
    assert env["TICKET_SECRET"] == name and env["MINT_TOKEN"] == "true"
    assert 'mint "$TICKET_SECRET" "" key 48' in job["spec"]["template"]["spec"]["containers"][0]["args"][0]

    def holders(doc):
        return [v for v in _pod(doc)["volumes"] if v.get("secret", {}).get("secretName") == name]

    deployments = {d["metadata"]["name"]: d for d in docs if d["kind"] == "Deployment"}
    for workload in ("t-group-sync-dashboard", "t-group-sync-dashboard-recovery"):
        (volume,) = holders(deployments[workload])
        assert volume["secret"]["items"] == [{"key": "key", "path": "key"}], "the dashboard signs with `key` alone"
    (volume,) = holders(deployments["t-group-sync-dashboard-report"])
    assert "items" not in volume["secret"], "the report pod also reads `previous` during a rotation"
    report = deployments["t-group-sync-dashboard-report"]["spec"]["template"]["spec"]["containers"][0]
    renv = {e["name"]: e.get("value") for e in report["env"]}
    assert renv["GSD_REPORT_TICKET_KEY_FILE"] == "/etc/gsd/report-ticket/key"
    assert renv["GSD_REPORT_TICKET_PREVIOUS_KEY_FILE"] == "/etc/gsd/report-ticket/previous"
    cronjobs = [d for d in docs if d["kind"] == "CronJob" and d["metadata"]["name"].startswith("t-group-sync-dashboard-report-")]
    assert len(cronjobs) == 2, [d["metadata"]["name"] for d in docs if d["kind"] == "CronJob"]
    for cj in cronjobs:
        assert not holders(cj), f"{cj['metadata']['name']} must never mount the ticket key"
        assert not [m for c in _pod(cj)["containers"] for m in c.get("volumeMounts", []) if "ticket" in m["mountPath"]]
    config = next(d for d in docs if d["kind"] == "ConfigMap" and d["metadata"]["name"] == "t-group-sync-dashboard-config")
    assert "reportingTicketKeyFile: /etc/gsd/report-ticket/key" in "".join(config["data"].values())


@pytest.mark.skipif(shutil.which("bash") is None, reason="bash not installed")
def test_t392_7_the_documented_rotation_moves_the_key_and_prints_no_value(tmp_path):
    """The chart README's two commands, run under an `oc` that records them: the open moves the current value to
    `previous`, writes a fresh 48-character key and restarts the report pod before the dashboard; the close removes
    `previous` and restarts the report pod. Neither prints a key."""
    readme = (CHART / "README.md").read_text()

    def block(marker: str) -> str:
        found = re.search(re.escape(marker) + r"\n````bash\n(?P<body>.*?)\n````\n", readme, re.S)
        assert found, marker
        return found.group("body")

    old = base64.b64encode(b"o" * 48).decode()
    shim = tmp_path / "bin"
    shim.mkdir()
    (shim / "oc").write_text("#!/bin/bash\n" f"printf '%s\\n' \"$*\" >> {tmp_path / 'calls'}\n"
                             f"case \"$*\" in 'get secret '*) printf '{old}' ;; esac\n")
    (shim / "oc").chmod(0o755)
    env = {**os.environ, "PATH": f"{shim}:{os.environ['PATH']}"}
    opened = subprocess.run(["bash", "-c", block("<!-- rotate the ticket key, open the window -->")], env=env,
                            capture_output=True, text=True, timeout=60)
    assert opened.returncode == 0, opened.stderr
    calls = (tmp_path / "calls").read_text().splitlines()
    patch = json.loads(next(c for c in calls if c.startswith("patch secret group-sync-dashboard-report-ticket-key"))
                       .split(" -p ", 1)[1])
    assert patch[0] == {"op": "add", "path": "/data/previous", "value": old}
    assert patch[1]["op"] == "replace" and patch[1]["path"] == "/data/key"
    new = base64.b64decode(patch[1]["value"])
    assert re.fullmatch(rb"[A-Za-z0-9]{48}", new) and new != b"o" * 48
    restarts = [c.split(" -n ")[0] for c in calls if c.startswith("rollout ")]
    assert restarts == ["rollout restart deployment/group-sync-dashboard-report",
                        "rollout status deployment/group-sync-dashboard-report",
                        "rollout restart deployment/group-sync-dashboard",
                        "rollout status deployment/group-sync-dashboard"], "the report pod restarts first"
    assert old not in opened.stdout + opened.stderr and patch[1]["value"] not in opened.stdout + opened.stderr
    (tmp_path / "calls").unlink()
    closed = subprocess.run(["bash", "-c", block("<!-- rotate the ticket key, close the window -->")], env=env,
                            capture_output=True, text=True, timeout=60)
    assert closed.returncode == 0 and not closed.stdout.strip(), closed.stdout + closed.stderr
    calls = (tmp_path / "calls").read_text().splitlines()
    assert calls[0].startswith("patch secret group-sync-dashboard-report-ticket-key")
    assert json.loads(calls[0].split(" -p ", 1)[1]) == [{"op": "remove", "path": "/data/previous"}]
    assert [c.split(" -n ")[0] for c in calls[1:]] == ["rollout restart deployment/group-sync-dashboard-report",
                                                       "rollout status deployment/group-sync-dashboard-report"]
