"""CSV as a fourth report format (docs/specs/SPEC_F2_csv_format.md, #106): one file per run, rendered
generically from the sealed report, carrying its sha256 and page one; the same cell becomes the same text as
in the page's table export (index.html `csvField`); off unless asked for."""
from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

import pytest
import yaml

from gsd.reporting import REPORT_PREFIX
from gsd.reporting.catalogue import REGISTRY, RunContext, validate_params
from gsd.reporting.catalogue.common import assemble
from gsd.reporting.config import ReportSettings, _formats_env
from gsd.reporting.model import KeyValues, Note, Report, Section, Table
from gsd.reporting.snapshot import Snapshot
from reporting_seed import CLUSTER, NOW, seed_store, write_snapshot
from test_p2_selectors import _FakeClient
from test_reporting_server import SERVICE, _viewer, _wait_done, service  # noqa: F401 — `service` is a fixture

LOCAL = Path(__file__).resolve().parents[1]
CHART = LOCAL.parent / "charts" / "group-sync-dashboard"
#: The page's export, verbatim from index.html (SPEC_C1). render_csv.csv_field is its port: a change to
#: either side fails T106-3 until the other follows.
JS_CSV_FIELD = r'''const CSV_BOM = "\ufeff";
function csvField(value) {
  if (value === null || value === undefined) return "";
  if (Array.isArray(value)) value = value.join("; ");
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return String(value);
  let s = String(value);
  // Tested after any leading whitespace: an importer that trims before it decides would treat
  // " =cmd" like "=cmd". The initiators are OWASP's — = + - @, tab, CR, LF — plus their
  // full-width forms (U+FF1D, U+FF0B, U+FF0D, U+FF20), which some locales' spreadsheets
  // evaluate too (review, C1). The cell keeps its original text; this only decides the prefix.
  if (/^[\t\r\n ]*[=+\-@\t\r\n\uFF1D\uFF0B\uFF0D\uFF20]/u.test(s)) s = "'" + s;
  if (/[",\r\n]/.test(s)) s = '"' + s.replace(/"/g, '""') + '"';
  return s;
}'''
#: Cells and the text both exports write for them (T106-2, T106-3).
CELLS = [
    ("=1+1", "'=1+1"), ("+1", "'+1"), ("-1", "'-1"), ("@SUM(A1)", "'@SUM(A1)"), ("\tx", "'\tx"),
    ("\rx", "\"'\rx\""), ("\nx", "\"'\nx\""), (" =x", "' =x"), ("＝x", "'＝x"), ("plain", "plain"),
    (" lead", " lead"), ("a,b", '"a,b"'), ('say "hi"', '"say ""hi"""'), ("", ""), (None, ""), (-1, "-1"),
    (0, "0"), (True, "true"), (False, "false"), (2.0, "2"), (0.5, "0.5"), (["a", "=b"], "a; =b"),
    (["=a", None, 3, True], "'=a; ; 3; true"), ([], ""),
]
PARAMS = {
    "namespace-access": {"namespaces": "prod-ns,dev-ns"},
    "access-certification": {"campaign": "Q3 2026", "due": "2026-10-01", "reviewer": "Jane Reviewer"},
}


def _render_csv(report: Report) -> str:
    from gsd.reporting.render_csv import render_csv   # imported here: before SPEC_F2 the module does not exist
    return render_csv(report)


def _synthetic() -> Report:
    return Report(
        name="t", title="Test report", cluster="c1", api_url="https://api.c1:6443", generated_at="2026-10-03T12:00:00Z",
        generated_by="alice", generated_by_note="proxy-verified", run_id="r1", params={}, coverage={}, provenance={},
        totals={}, truncated=False, include_members=False,
        sections=[
            Section("Provenance and coverage", [KeyValues("Run", [("Run id", "r1"), ("Generated by", "alice")]),
                                                Note("Scope: direct bindings only.", "caveat")], sealed=False),
            Section("Findings", [Table("Grants", ["Subject", "Count", "Reason"],
                                       [['=HYPERLINK("x")', 3, None], ["a, b", -1, "line\nbreak"]], note="2 rows"),
                                 Table("Empty", ["Name"], [], empty_text="none found")]),
        ]).seal()


def test_t106_1_the_renderer_walks_a_table_a_list_and_a_note():
    """Every block kind, in order, under its label record; page one marked not sealed; the sha256 printed.
    Without SPEC_F2: ModuleNotFoundError, gsd.reporting.render_csv."""
    report = _synthetic()
    expected = [
        "﻿Report,Test report", f"sha256 of the report data,{report.sha256}",
        "", "Section,Provenance and coverage,not sealed: states the run",
        "", "List,Run", "Run id,r1", "Generated by,alice",
        "", "Caveat,Scope: direct bindings only.",
        "", "Section,Findings,sealed",
        "", "Table,Grants", "Subject,Count,Reason", "\"'=HYPERLINK(\"\"x\"\")\",3,", '"a, b",-1,"line\nbreak"', "Note,2 rows",
        "", "Table,Empty", "Name", "none found",
    ]
    assert _render_csv(report) == "\r\n".join(expected) + "\r\n"


@pytest.mark.parametrize(("value", "text"), CELLS)
def test_t106_2_a_formula_leading_cell_is_neutralised(value, text):
    """OWASP's initiators (and the browser's LF and full-width forms) get an apostrophe; numbers and booleans
    are never touched. Without SPEC_F2: ModuleNotFoundError."""
    from gsd.reporting.render_csv import csv_field
    assert csv_field(value) == text


def test_t106_3_the_port_is_the_browser_export():
    """The same cell becomes the same text in both CSV exports. The JavaScript is pinned verbatim, so a change
    to the page's export fails here; where node is installed, both functions run over the same cells.
    Without SPEC_F2: ModuleNotFoundError (the pin itself holds on main)."""
    from gsd.reporting.render_csv import CSV_BOM, csv_field
    page = (LOCAL / "gsd" / "static" / "index.html").read_text(encoding="utf-8")
    start = page.index("const CSV_BOM")
    assert page[start:page.index("\n}\n", start) + 2] == JS_CSV_FIELD, "index.html's csvField changed: port it"
    assert CSV_BOM == "﻿" and 'return CSV_BOM + lines.join("\\r\\n") + "\\r\\n";' in page
    values = [value for value, _ in CELLS]
    ported = [csv_field(value) for value in values]
    assert ported == [text for _, text in CELLS]
    node = shutil.which("node")
    if node:
        script = JS_CSV_FIELD + "\nprocess.stdout.write(JSON.stringify(JSON.parse(process.argv[1]).map(csvField)));"
        ran = subprocess.run([node, "-e", script, "--", json.dumps(values)], capture_output=True, text=True, timeout=30, check=True)
        assert json.loads(ran.stdout) == ported


def _report(snap: Snapshot, name: str) -> Report:
    spec, build = REGISTRY[name]
    info = snap.info()
    ctx = RunContext(settings=ReportSettings(login_capture_enabled=True), cluster=snap.cluster(CLUSTER), now=NOW,
                     run_id="20260906T120000.000000Z-ab12", generated_by="alice", generated_by_note="proxy-verified",
                     snapshot_stamp=info.stamp, snapshot_age_seconds=info.age_seconds(NOW), schema_version=info.schema_version)
    params = validate_params(spec, PARAMS.get(name, {}))
    return assemble(spec, snap, ctx, params, build(snap, ctx, params))


def test_t106_4_every_report_renders_with_its_seal_and_page_one(tmp_path):
    """All eleven reports through the one generic renderer: the sha256 the .json carries, page one's rows,
    one Section record per section, and the seal unchanged by rendering. Without SPEC_F2: ModuleNotFoundError."""
    store = seed_store(str(tmp_path / "writer.db"))
    (tmp_path / "snapshots").mkdir()
    try:
        snap = Snapshot(write_snapshot(store, tmp_path / "snapshots"))
    finally:
        store.close()
    with snap:
        for name in REGISTRY:
            report = _report(snap, name)
            sealed = report.sha256
            text = _render_csv(report)
            lines = text.split("\r\n")
            assert lines[:2] == [f"﻿Report,{report.title}", f"sha256 of the report data,{sealed}"], name
            assert json.loads(report.to_json())["sha256"] == sealed == report.seal().sha256, name
            assert lines[3] == "Section,Provenance and coverage,not sealed: states the run", name
            assert f"Run id,{report.run_id}" in lines, name
            assert sum(line.startswith("Section,") for line in lines) == len(report.sections), name


def test_t106_5_a_run_stores_and_serves_csv(service):  # noqa: F811
    """`csv` is accepted, rendered after the .json, stored as report.csv in the run's own directory and served
    as text/csv with a .csv name. Without SPEC_F2: 422 (create_run's allow-set is html and pdf)."""
    client, app, _ = service
    r = client.post(f"{REPORT_PREFIX}/api/runs", json={"report": "groups", "cluster": CLUSTER, "formats": ["csv"]}, headers=_viewer())
    assert r.status_code == 202, r.text
    run = _wait_done(client, r.json()["id"], _viewer())
    assert run["status"] == "done", run.get("error")
    assert run["formats"] == ["csv"] and set(run["bytes"]) == {"json", "csv"}
    a = client.get(f"{REPORT_PREFIX}/api/runs/{run['id']}/artifact", params={"format": "csv"}, headers=_viewer())
    assert a.status_code == 200 and a.headers["content-type"] == "text/csv; charset=utf-8; header=absent"
    assert a.headers["content-disposition"].startswith('attachment; filename="gsd_') and a.headers["content-disposition"].endswith('.csv"')
    assert a.headers["x-gsd-report-sha256"] == run["sha256"]
    assert a.content.startswith("﻿Report,".encode()) and f"sha256 of the report data,{run['sha256']}\r\n".encode() in a.content
    assert len(a.content) == run["bytes"]["csv"]
    # the store's layout: one directory per run, one file per format beside the manifest
    assert sorted(p.name for p in (app.state.store.root / run["id"]).iterdir()) == ["report.csv", "report.json", "run.json"]


def test_t106_6_create_run_refuses_xlsx_and_the_settings_accept_csv(service, monkeypatch):  # noqa: F811
    """`xlsx` stays refused; `csv` is a word the deployment may list. Without SPEC_F2 `_formats_env` refuses
    `csv` at startup (SystemExit)."""
    client, _, _ = service
    r = client.post(f"{REPORT_PREFIX}/api/runs", json={"report": "groups", "cluster": CLUSTER, "formats": ["csv", "xlsx"]}, headers=_viewer())
    assert r.status_code == 422 and "xlsx" in r.json()["detail"], r.text
    monkeypatch.setenv("GSD_REPORT_FORMATS_SCHEDULED", "html,json,csv")
    assert _formats_env("GSD_REPORT_FORMATS_SCHEDULED", ("html",)) == ("html", "csv")
    monkeypatch.setenv("GSD_REPORT_FORMATS_SCHEDULED", "html,xlsx")
    with pytest.raises(SystemExit):
        _formats_env("GSD_REPORT_FORMATS_SCHEDULED", ("html",))


def test_t106_7_csv_is_off_unless_configured(service):  # noqa: F811
    """The defaults name no csv: the service's settings, the chart's values, and what a request naming no
    formats stores. Passes before and after SPEC_F2: it guards the issue's "Must not change"."""
    assert ReportSettings().formats_scheduled == ("html",) and ReportSettings().formats_manual == ("html", "pdf")
    values = yaml.safe_load((CHART / "values.yaml").read_text())["reporting"]["formats"]
    assert values == {"scheduled": ["html", "json"], "manual": ["html", "json", "pdf"]}
    client, _, _ = service
    manual = client.post(f"{REPORT_PREFIX}/api/runs", json={"report": "groups", "cluster": CLUSTER}, headers=_viewer()).json()
    scheduled = client.post(f"{REPORT_PREFIX}/api/runs", json={"report": "groups", "cluster": CLUSTER, "schedule": "nightly"},
                            headers=SERVICE).json()
    assert manual["formats"] == ["html", "pdf"] and scheduled["formats"] == ["html"]


def test_t106_8_the_schedule_trigger_takes_csv(monkeypatch, tmp_path):
    """A schedule's `formats: [csv]` reaches the run. Without SPEC_F2 argparse refuses the choice (exit 2)."""
    from gsd.reporting import trigger
    token = tmp_path / "token"
    token.write_text("secret")
    monkeypatch.setattr(trigger.httpx, "Client", _FakeClient)
    rc = trigger.main(["--url", "https://x", "--report", "groups", "--schedule", "weekly", "--token-file", str(token),
                       "--format", "html", "--format", "csv"])
    assert rc == 0 and _FakeClient.captured["json"]["formats"] == ["html", "csv"]
