apiVersion: v1
kind: Service
metadata:
  labels:
    app: mock-openshift
  name: mock-openshift
spec:
  ports:
  - name: https
    port: 6443
    protocol: TCP
    targetPort: 6443
  selector:
    app: mock-openshift
  type: ClusterIP

