apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-onboarding
  namespace: group-sync-dashboard
  labels:
    groupsync-dashboard.io/config-type: onboard
data:
  clusters.yaml: |
    clusters:
      - name: cm-demo-a
        apiUrl: https://api.crc.testing:6443
        saTokenLookup: true
      - name: cm-demo-b
        apiUrl: https://192.168.127.2:6443
        saTokenLookup: true
        insecureSkipVerify: true
